version: '1.0'
services:
  frontend:
    build: 
      context: .
      dockerfile: ./apps/frontend/DOCKERFILE
    ports:
      - "5172:80"
    depends_on:
      - backend

  backend:
    build: 
      context: .
      dockerfile: ./apps/backend/DOCKERFILE
    ports:
      - "3000:3000"
    env_file:
      - ./apps/backend/.env
    depends_on:
      - database

  database:
    image: postgres:alpine
    container_name: postgres
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./apps/backend/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  postgres_data: